
name: Deploy to Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Surge
        run: npm install -g surge
      
      - name: Deploy to Surge
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_TOKEN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }}